# Generated by Django 3.1.2 on 2021-03-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=32)),
                ('crypto_currency_name', models.CharField(max_length=5)),
                ('money_currency_name', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_time', models.DateTimeField()),
            ],
        ),
    ]
